In [1]:
import torch
import numpy as np

In [2]:
np.set_printoptions(precision=3) #show up to and including the 3rd decimal place for numpy objects

In [3]:
a = [1, 2, 3] #list
b = np.array([4, 5, 6], dtype=np.int32) #numpy array

t_a = torch.tensor(a) #creating a tensor from the list
t_b = torch.from_numpy(b) #creating a tensor from the array

print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [4]:
torch.is_tensor(a), torch.is_tensor(t_a) #showing if object is a tensor

(False, True)

In [5]:
t_ones = torch.ones(2, 3) #creating a 2d tensor of dimensions 2x3 with 1s for every position

t_ones.shape #showing the shape with is 2x3, 2y and 3x

torch.Size([2, 3])

In [6]:
print(t_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
rand_tensor = torch.rand(2,3) #creating a 2x3 matrix of random generated values that exist in [0,1]

print(rand_tensor)

tensor([[0.7707, 0.6064, 0.1144],
        [0.0413, 0.8118, 0.1971]])


In [8]:
print(t_a)
print(t_a.dtype)

tensor([1, 2, 3])
torch.int64


In [9]:
t_a_new = t_a.to(torch.int64) #change datatype to a different one

print(t_a_new.dtype)

torch.int64


In [10]:
t = torch.rand(3, 5)
print(t)
t_tr = torch.transpose(t, 0, 1) #making t_tr the transpose of t
print(t.shape, ' --> ', t_tr.shape)
print(t_tr)

tensor([[0.6450, 0.7643, 0.2431, 0.2857, 0.6120],
        [0.0145, 0.3652, 0.3428, 0.3500, 0.0089],
        [0.3140, 0.4772, 0.8838, 0.4231, 0.4651]])
torch.Size([3, 5])  -->  torch.Size([5, 3])
tensor([[0.6450, 0.0145, 0.3140],
        [0.7643, 0.3652, 0.4772],
        [0.2431, 0.3428, 0.8838],
        [0.2857, 0.3500, 0.4231],
        [0.6120, 0.0089, 0.4651]])


In [11]:
t = torch.zeros(30) #making a 1d tensor of 30 0s
print(t)
t_reshape = t.reshape(5, 6) #reshape so that the 0s are 5y by 6x of a 2d tensor
print(t_reshape)
print(t_reshape.shape)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
torch.Size([5, 6])


In [12]:
t = torch.zeros(1, 2, 1, 4, 1)
t_sqz = torch.squeeze(t, 2)

print(t.shape, ' --> ', t_sqz.shape)

torch.Size([1, 2, 1, 4, 1])  -->  torch.Size([1, 2, 4, 1])


In [13]:
t = torch.zeros(2,1)
print(t)
t_sqz = torch.squeeze(t) #Removing the unnecessary dimensions (dimensions that have size 1, which are not needed)
print(t_sqz)

tensor([[0.],
        [0.]])
tensor([0., 0.])


In [14]:
torch.manual_seed(1)

t1 = 2 * torch.rand(5, 2) - 1 #uniform distribution from [-1, 1)
print(t1)
t2 = torch.normal(mean=0, std=1, size=(5, 2)) #normal distribution with std of 1
print(t2)

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])


In [15]:
t3 = torch.multiply(t1, t2) #element wise matrix multiplication
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [16]:
t4 = torch.mean(t1, axis=0) #mean of each column
print(t4)

tensor([-0.1373,  0.2028])


In [17]:
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1)) #matrix dot product

print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [18]:
t1

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])

In [19]:
torch.transpose(t2, 0, 1)

tensor([[ 0.8590, -0.3406, -1.1948, -0.7627, -0.3245],
        [ 0.7056, -1.2720,  0.0250,  1.3969,  0.2879]])

In [20]:
t6 = torch.matmul(torch.transpose(t1, 0, 1), t2)

print(t6)

tensor([[ 1.7453,  0.3392],
        [-1.6038, -0.2180]])


In [21]:
torch.transpose(t1, 0, 1)

tensor([[ 0.5153, -0.1939, -0.9414, -0.2057,  0.1390],
        [-0.4414,  0.4694,  0.5997,  0.5087, -0.1224]])

In [22]:
t2

tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])

In [23]:
t1

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])

In [24]:
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1) #L^P norm of t1 tensor. Here is L^2

print(norm_t1)

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])


In [25]:
print(np.sqrt(np.sum(np.square(t1.numpy()), axis=1)))

[0.678 0.508 1.116 0.549 0.185]


In [26]:
torch.manual_seed(1)
t = torch.rand(6) #tensor of randomly generated [0-1] numbers
print(t)
t_splits = torch.chunk(t, 3) #split the tensor into 3 even tensors where t_splits is a list of tensors
[item.numpy() for item in t_splits]

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])


[array([0.758, 0.279], dtype=float32),
 array([0.403, 0.735], dtype=float32),
 array([0.029, 0.8  ], dtype=float32)]

In [27]:
t_splits[0]

tensor([0.7576, 0.2793])

In [28]:
t_splits[1]

tensor([0.4031, 0.7347])

In [29]:
torch.manual_seed(1)
t = torch.rand(5) #tensor of randomly generated [0-1] numbers
print(t)
t_splits = torch.split(t, split_size_or_sections=[3, 2]) #split the tensor into a tensor of 3 and a tensor of 2 and save into a list of tensors
[item.numpy() for item in t_splits]

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])


[array([0.758, 0.279, 0.403], dtype=float32),
 array([0.735, 0.029], dtype=float32)]

In [30]:
A = torch.ones(3) #tensor of 3 1s
print(A)
B = torch.zeros(2) #tensor of 2 0s
print(B)
C = torch.cat([A, B], axis=0) #concatinating tensors, thus 1d tensor of size 5
print(C)

tensor([1., 1., 1.])
tensor([0., 0.])
tensor([1., 1., 1., 0., 0.])


In [31]:
A = torch.ones(3) #tensor of 3 1s
print(A)
B = torch.zeros(3) #tensor of 3 0s
print(B)
S = torch.stack([A, B], axis=1) #stacking tensors, thus a 2d tensor
print(S)

tensor([1., 1., 1.])
tensor([0., 0., 0.])
tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])


In [32]:
from torch.utils.data import DataLoader

t = torch.arange(6, dtype=torch.float32) #1d tensor of values 0-5
print(t)
data_loader = DataLoader(t) #create a dataset using dataloader and t tensor

tensor([0., 1., 2., 3., 4., 5.])


In [33]:
for item in data_loader:
    print(item)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [34]:
data_loader = DataLoader(t, batch_size=3, drop_last=False) #creating batch size of 3 from dataset

for i, batch in enumerate(data_loader, 1):
    print(f'batch {i}:', batch)

batch 1: tensor([0., 1., 2.])
batch 2: tensor([3., 4., 5.])


In [35]:
torch.manual_seed(1)
t_x = torch.rand([4, 3], dtype=torch.float32)
t_y = torch.arange(4)

In [36]:
t_x #tensor with features

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247]])

In [37]:
t_y #tensor with class labels

tensor([0, 1, 2, 3])

In [38]:
from torch.utils.data import Dataset

class JointDataset(Dataset): #defining a custom dataset class
    def __init__(self, x, y): #This is where the initial logic happens, such as reading existing arrays, loading a
#file, filtering data, and so forth.
        self.x = x
        self.y = y
    def __len__(self):
        return len(self.x)
    def __getitem__(self, idx): #This returns the corresponding sample to the given index.
        return self.x[idx], self.y[idx]

In [39]:
joint_dataset = JointDataset(t_x, t_y) #create a joint dataset with the custom dataset class

In [40]:
for example in joint_dataset: #print each example of the joint dataset
    print('  x: ', example[0],
          '  y: ', example[1])

  x:  tensor([0.7576, 0.2793, 0.4031])   y:  tensor(0)
  x:  tensor([0.7347, 0.0293, 0.7999])   y:  tensor(1)
  x:  tensor([0.3971, 0.7544, 0.5695])   y:  tensor(2)
  x:  tensor([0.4388, 0.6387, 0.5247])   y:  tensor(3)


In [41]:
joint_dataset[0]

(tensor([0.7576, 0.2793, 0.4031]), tensor(0))

In [42]:
joint_dataset[1]

(tensor([0.7347, 0.0293, 0.7999]), tensor(1))

In [43]:
torch.manual_seed(1)
data_loader = DataLoader(dataset=joint_dataset, batch_size=2, shuffle=True) #creating a dataloader which shuffles the order, here each batch is 2

In [44]:
for i, batch in enumerate(data_loader, 1):
        print(f'batch {i}:', 'x:', batch[0],
              '\n         y:', batch[1])

batch 1: x: tensor([[0.3971, 0.7544, 0.5695],
        [0.7576, 0.2793, 0.4031]]) 
         y: tensor([2, 0])
batch 2: x: tensor([[0.7347, 0.0293, 0.7999],
        [0.4388, 0.6387, 0.5247]]) 
         y: tensor([1, 3])


In [45]:
for epoch in range(2): #when training a model for multiple epochs, we need to shuffle and iterate over the dataset by the desired number of epochs. So, let’s iterate over the batched dataset twice
    print(f'epoch {epoch+1}')
    for i, batch in enumerate(data_loader, 1):
        print(f'batch {i}:', 'x:', batch[0],
              '\n         y:', batch[1])

epoch 1
batch 1: x: tensor([[0.7576, 0.2793, 0.4031],
        [0.3971, 0.7544, 0.5695]]) 
         y: tensor([0, 2])
batch 2: x: tensor([[0.7347, 0.0293, 0.7999],
        [0.4388, 0.6387, 0.5247]]) 
         y: tensor([1, 3])
epoch 2
batch 1: x: tensor([[0.4388, 0.6387, 0.5247],
        [0.3971, 0.7544, 0.5695]]) 
         y: tensor([3, 2])
batch 2: x: tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]]) 
         y: tensor([0, 1])


In [46]:
#creating a list of image files
import pathlib
imgdir_path = pathlib.Path('/Users/haydenlabrie/PycharmProjects/machine_learning_book/machine-learning-book-main/ch12/cat_dog_images')
file_list = sorted([str(path) for path in imgdir_path.glob('*.jpg')])
print(file_list)

['/Users/haydenlabrie/PycharmProjects/machine_learning_book/machine-learning-book-main/ch12/cat_dog_images/cat-01.jpg', '/Users/haydenlabrie/PycharmProjects/machine_learning_book/machine-learning-book-main/ch12/cat_dog_images/cat-02.jpg', '/Users/haydenlabrie/PycharmProjects/machine_learning_book/machine-learning-book-main/ch12/cat_dog_images/cat-03.jpg', '/Users/haydenlabrie/PycharmProjects/machine_learning_book/machine-learning-book-main/ch12/cat_dog_images/dog-01.jpg', '/Users/haydenlabrie/PycharmProjects/machine_learning_book/machine-learning-book-main/ch12/cat_dog_images/dog-02.jpg', '/Users/haydenlabrie/PycharmProjects/machine_learning_book/machine-learning-book-main/ch12/cat_dog_images/dog-03.jpg']


In [ ]:
#visualizing images
import matplotlib.pyplot as plt
import os
from PIL import Image


fig = plt.figure(figsize=(10, 5))
for i, file in enumerate(file_list):
    img = Image.open(file)
    print('Image shape: ', np.array(img).shape)
    ax = fig.add_subplot(2, 3, i+1)
    ax.set_xticks([]); ax.set_yticks([])
    ax.imshow(img)
    ax.set_title(os.path.basename(file), size=15)

#plt.savefig('figures/12_03.pdf')
plt.tight_layout()
plt.show()

Image shape:  (900, 1200, 3)
Image shape:  (900, 1200, 3)
Image shape:  (900, 742, 3)
Image shape:  (800, 1200, 3)
Image shape:  (800, 1200, 3)
Image shape:  (900, 1200, 3)


In [ ]:
#getting class labels from file name
labels = [1 if 'dog' in os.path.basename(file) else 0
          for file in file_list]
print(labels)

In [ ]:
#creating function to join the file name and class label datasets together
class ImageDataset(Dataset):
    def __init__(self, file_list, labels):
        self.file_list = file_list
        self.labels = labels

    def __getitem__(self, index):
        file = self.file_list[index]
        label = self.labels[index]
        return file, label

    def __len__(self):
        return len(self.labels)

image_dataset = ImageDataset(file_list, labels)
for file, label in image_dataset:
    print(file, label)

In [ ]:
#resize the images and convert to tensors
import torchvision.transforms as transforms
img_height, img_width = 80, 120
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Resize((img_height, img_width)),
])

In [ ]:
#update class with image transformation defined above
class ImageDataset(Dataset):
    def __init__(self, file_list, labels, transform=None):
        self.file_list = file_list
        self.labels = labels
        self.transform = transform
    def __getitem__(self, index):
        img = Image.open(self.file_list[index])
        if self.transform is not None:
            img = self.transform(img)
        label = self.labels[index]
        return img, label
    def __len__(self):
        return len(self.labels)
image_dataset = ImageDataset(file_list, labels, transform)

In [ ]:
image_dataset[4] #0-2 is cat and 3-5 is dog

In [ ]:
#showing transformed images
fig = plt.figure(figsize=(10, 6))
for i, example in enumerate(image_dataset):
    ax = fig.add_subplot(2, 3, i + 1)
    ax.set_xticks([]); ax.set_yticks([])
    ax.imshow(example[0].numpy().transpose((1, 2, 0)))
    ax.set_title(f'{example[1]}', size=15)

plt.tight_layout()
plt.savefig('figures/12_04.pdf')
plt.show()

In [ ]:
import torchvision

In [ ]:
image_path = ''
#spliting into train, validate, and test sets. Only load the train set to use rn. We are only using the attribute 
#as the target. The target is the y variable. The attributes are facial expression, makeup, hair properties ...
celeba_dataset = torchvision.datasets.CelebA(image_path, split='train', target_type='attr', download=False)

assert isinstance(celeba_dataset, torch.utils.data.Dataset)

In [ ]:
example = next(iter(celeba_dataset))
print(example) #using smiling which is the 31st element of the attribute vector

In [ ]:
#plotting the x = image and  y = class label, which is the smiling attribute
from itertools import islice
fig = plt.figure(figsize=(12, 8))
for i, (image, attributes) in islice(enumerate(celeba_dataset), 18):
    ax = fig.add_subplot(3, 6, i+1)
    ax.set_xticks([]); ax.set_yticks([])
    ax.imshow(image)
    ax.set_title(f'{attributes[31]}', size=15)
    
#plt.savefig('figures/12_05.pdf')
plt.show()

In [ ]:
mnist_dataset = torchvision.datasets.MNIST(image_path, 'train', download=True) #download the training porisition of
#the mnist dataset

assert isinstance(mnist_dataset, torch.utils.data.Dataset)

example = next(iter(mnist_dataset))
print(example)
#printing the x = image and y= class label, being number that maps to the image 
fig = plt.figure(figsize=(15, 6))
for i, (image, label) in islice(enumerate(mnist_dataset), 10):
    ax = fig.add_subplot(2, 5, i+1)
    ax.set_xticks([]); ax.set_yticks([])
    ax.imshow(image, cmap='gray_r')
    ax.set_title(f'{label}', size=15)

#plt.savefig('figures/12_06.pdf')
plt.show()